
# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Travellin.Api.csproj", "."]
RUN dotnet restore "Travellin.Api.csproj"
COPY . .
RUN dotnet build "Travellin.Api.csproj" -c Release -o /app/build


# Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish ./publish .
ENTRYPOINT ["dotnet", "Travellin.Api.dll"]